name: zCloud CLI test
on:
  push:
    branches: ['main']

jobs:
  deploy-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zcloud-ws/zcloud-deploy-action@main
        with:
          user-token: aszkgzh369gnbkt45-lrguzqdzmfwuku86v
          env: joaovictornsv-docker-httpd-v1-production
          dir: v1
      - uses: zcloud-ws/zcloud-deploy-action@main
        with:
          user-token: aszkgzh369gnbkt45-lrguzqdzmfwuku86v
          env: joaovictornsv-docker-httpd-v2-production
          dir: v2
